name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-workflow-execution:
    strategy:
      matrix:
        test:
          - name: Self Validation
            schema: https://json.schemastore.org/github-action.json
            paths: ./action.yaml
            scope: all
            expect-pass: true
          - name: github-action Validation
            schema: https://json.schemastore.org/github-action.json
            paths: ./**/action.yaml
            scope: all
            expect-pass: true
          - name: github-workflow Validation
            schema: https://json.schemastore.org/github-workflow.json
            paths: ./.github/workflows/*.yaml
            scope: all
            expect-pass: true
          - name: Bad Action
            schema: https://json.schemastore.org/github-action.json
            paths: ./.github/bad-action.yaml
            scope: all
            expect-pass: false
          - name: Diff github-action Validation
            schema: https://json.schemastore.org/github-action.json
            paths: ./**/action.yaml
            scope: diff
            expect-pass: true

    name: Test ${{ matrix.test.name }}
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    with:
      schema: ${{ matrix.test.schema }}
      paths: ${{ matrix.test.paths }}
      expect-pass: ${{ matrix.test.expect-pass }}
      scope: ${{ matrix.test.scope }}

  convenience-github-workflow:
    name: Test github-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate JSON Schema
        uses: ./github-workflow
        with:
          paths: .github/workflows/*.yaml
          cache-key: github-workflow
          scope: all

  convenience-github-action:
    name: Test github-action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate JSON Schema
        uses: ./github-action
        with:
          paths: |
            ./github-*/action.yaml
            ./cargo/action.yaml
            ./action.yaml
          cache-key: github-action
          scope: all
