name: Test JSON Schema action

permissions:
  contents: read
  issues: read
  pull-requests: read

on:
  workflow_call:
    inputs:
      schema:
        description: The JSON Schema file or URL to use for the test
        required: true
        type: string
      paths:
        description: The input file path(s) to validate
        required: true
        type: string
      expect-pass:
        description: Whether the test is expected to pass or fail
        required: true
        type: boolean
      cache-key:
        description: The cache key to use for caching the action
        required: false
        type: string
        default: ''
      scope:
        description: The scope of files to ignore for validation
        required: false
        type: string
        default: 'all'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate JSON Schema
        id: validate
        uses: ./
        continue-on-error: ${{ !inputs.expect-pass }}
        with:
          schema: ${{ inputs.schema }}
          paths: ${{ inputs.paths }}
          cache-key: ${{ inputs.cache-key }}
          scope: ${{ inputs.scope }}

      - name: Check the result
        if: ${{ always() && !inputs.expect-pass }}
        shell: bash
        run: |
          if ${{ steps.validate.outputs.status == 'success' }}; then
            exit 1
          fi
